### ISSUE TITLE
3rd Party Apps: Samsung Fascinate only volume buttons work

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#32]
as reported in Gadgeteer review:  http://the-gadgeteer.com/2012/02/18/digital-innovations-universal-speaker-dock-for-android-review/

**Comment by syalam** [comment]
He is probably running a music player we don't support (com.android.music). I really want to filter this out from our media player list so reviewers/users don't encounter it, but unfortunately, it could also be the primary player for most people.

com.android.music also known as (Music [not to be confused with Google music], or HTC Music on certain devices) is the default Android music player, and as noted before via e-mails, I checked out the source code for this app on android.org (open source android code) and there is a bit of code that rejects remote broadcasts. It handles Volume controls because Android treats those as system level commands and not intent level broadcasts that 3rd parties consume.

I have a Samsung Fascinate that works with Winamp/Pandora/Amazon MP3/Spotify.

**Comment by JoeBorn** [comment]
ok, please verify that this is the case with the reviewer.  If you have trouble let me know.

**Comment by syalam** [comment]
NP. Following up.

**Comment by syalam** [comment]
James responded with the following:

"Let me try Pandora and Winamp, I will add them to the review as well if I can.  I will let you know how they work, I should be using those anyway becasue I am not a big fan of stock players"

He was presumably using the stock player (com.android.music).

**Comment by pdattaSonr** [comment]
Merged with #36 due to similar bucket of problem nature.
