### ISSUE TITLE
SONR App Does Not Work  (#issues = 3)

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#34]
a) On both Motorola Droid RAZR MAXX and LG Spectrum
Per mobile tech review: http://www.mobiletechreview.com/ubbthreads/showflat.php?Number=42138

b) app stopped working after update
Reported by Customer Shannon Durham - shannon@bayphoto.com 

c) app won't work with husband's phone
jg1ht0rvnj4t3cc@marketplace.amazon.com

**Comment by syalam** [comment]
My initial thoughts:

Motorola Droid RAZR MAXX runs Ice Cream Sandwich (4.0). I think Dean mentioned there was some erratic behavior on his phone. In the Android documentation there is a clear change in how intents are sent in Ice Cream Sandwich. The current code is setup to take advantage of ICS intent broadcasting mechanism (though it hasn't been tested since we don't have any 4.0 devices on hand).

LG Spectrum is running a "custom version of Gingerbread" according to this review http://www.trustedreviews.com/lg-spectrum_Mobile-Phone_review I am wondering if that has anything to do with SONR not working.

**Comment by JoeBorn** [comment]
RAZR MAXX does not yet appear to have ICS.  I'll enter a separate issue on more advanced debugging.

**Comment by pdattaSonr** [comment]
Updated heading and changed label to showstopper
