### ISSUE TITLE
MicSerialListener blocks the main thread

### ISSUE THREAD

**Issue by syalam** [JoeBorn/sonr#6]
1. Select Media Player
2. Hit OK
3. Notice UI freezes temporarily.

**Comment by reshapiro** [comment]
At some point SONRClient#searchSignal() will need an option to run asynchronously. Right now we use this method in a few different contexts, some of which have to be synchronous, since we don't want proceed if the dock is not detected, and others of which should be asychronous, since they're triggered by touch actions on the phone screen and we don't want to lockup the ui.  The first step in fixing this is determinig which is which.

**Comment by reshapiro** [comment]
Should be fixed now in master.  There were two places where a dock search might have been invoked in the main thread via a button click.  Both now use a work thread for the search, and the main thread for any response (eg showing Dock Found or Dock Not Found).
