### ISSUE TITLE
Dock Not Detected After Pressing Android Home Button

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#7]
1. Launch SONR
2. Select Media Player
3. Play Music
4. Click HOME on ANDROID DEVICE
5. Launch SONR again
6. Select Media Player
7. DOCK NOT DETECTED

**Comment by syalam** [comment]
This is most probably because dock detection etc is being done onCreate() which only gets called once. When an app comes back from a resumed state it skips onCreate() and goes to onResume(). No code ever gets executed that checks if the dock is active, and is therefore false. This is the basic premise.

**Comment by syalam** [comment]
Definitely an Android Lifecycle/State issue. If you rotate your phone everything works again. This is because onCreate() is called again when you switch orientation
