### ISSUE TITLE
Playback "skipping" with 0.57 build

### ISSUE THREAD

**Issue by syalam** [JoeBorn/sonr#9]
SHA: e4e5bd10ca05fa8cdc2ba26ef86971d6f626d8a3

Tester: Johan
Phone: Motorola Atrix
Build: 0.57
Music Players: Google Music, HTC Music, Amazon MP3

Description: Playback is distorted and "skips" after some time.

**Comment by reshapiro** [comment]
I can't replicate this with Pandora or Music on the Samsung and my home wireless router.

It could be a thread starvation problem, in other words the SONR audio-processor thread might not giving other threads enough opportunity to run.  This sort of thing could easiy be specific to particular phones and also to network connectivity conditions (3G signal strength, other activity on the wireless connection). 

We can have this thread yield from time to time to give other threads a chance to run, but a possible side-effect would be slower response to remote-control operations.  I have a version like this in a local branch we can use for testing.

We should also verify that Johan doesn't have exactly the same problem when he runs Amazon etc without SONR.  Maybe he just doesn't have a good enough connection for music streaming, or didn't have when he ran into this.

**Comment by syalam** [comment]
Sent Johan a note about testing without running SONR

**Comment by syalam** [comment]
Johan is not streaming music or playing off of the network. We should test a thread yielding solution and see if there are any trade-offs.

**Comment by reshapiro** [comment]
This is suspicous.  Google Music is a cloud-based app, and so is Amazon as far as I know, at least by default.  Are we sure Johan understands when music is local and when it isn't?
In any case, he still needs to test these apps without SONR.   Until he does that, or we can replicate the bug here, this sounds like a user or network problem,  not a SONR problem.

I will do a quick test a variant of 'master' that has a yield and if it seems to work in general, bundle it to Sheehan for more serious testing.

**Comment by syalam** [comment]
Johan is reporting that the thread yielding is better, but still encounters skipping after a couple of hours on the Atrix.

I will be receiving an Atrix soon to test on. Putting this issue on hold for now until we can reliably test.
